# 运行 Nginx 工作进程的用户
user  nginx;
# 工作进程数，auto 表示自动根据 CPU 核心数启动对等数量的进程
worker_processes  auto;

# 全局错误日志的存放路径和级别（notice表示通知级别以上）
error_log  /var/log/nginx/error.log notice;
# 记录 Nginx 主进程 ID 的文件
pid        /var/run/nginx.pid;


events {
    # 每个工作进程允许的最大并发连接数
    worker_connections  1024;
}


http {
    # 引入外部文件，里面包含各种文件扩展名与对应的 MIME 类型的映射（告诉浏览器这是图片还是 html）
    include       /etc/nginx/mime.types;
    # 默认的数据传输类型：二进制流（比如浏览器遇到不认识的文件，就会弹窗下载）
    default_type  application/octet-stream;

    # 定义了一套名为 'main' 的访问日志格式，包含了客户端 IP、时间、请求内容、状态码、网页来源及浏览器标识等
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # 明确访问日志存放在哪里，并使用上面定义的 'main' 格式
    access_log  /var/log/nginx/access.log  main;

    # 开启高效文件传输模式，直接在操作系统内核中复制数据，而不需要经过 Nginx 进程内存，极大地提高了静态文件的分发速度
    sendfile        on;
    #tcp_nopush     on;

    # 客户端保持活动连接（Keep-Alive）的超时时间。65秒内没操作这根连接就断开
    keepalive_timeout  65;

    # gzip可以开启网页文件压缩，加快网页打开速度（这里被注释掉了没有管）
    #gzip  on;

    # 关键：加载外部子配置文件。会把 /etc/nginx/conf.d 目录下所有的 .conf 文件的内容都载入进来（包括你的 localhost.conf）
    include /etc/nginx/conf.d/*.conf;
}